// User Actions
export const SET_USER = "SET_USER";
export const TOGGLE_AUTHENTICATING = "TOGGLE_AUTHENTICATING";
export const LOGOUT_USER = "LOGOUT_USER";
export const UPLOAD_EXCEL = "UPLOAD_EXCEL";
export const DATALIST = "DATALIST";
export const USERDATALIST = "USERDATALIST";
export const CREATEUSER = "CREATEUSER";
export const CREATEACCESSMANAGER = "CREATEACCESSMANAGER";
export const LISTACCESSMANAGER = "LISTACCESSMANAGER";
export const FORGETUSER = "FORGETUSER";
export const RESETPASSWORD = "RESETPASSWORD";
export const CHANGEAPI = "CHANGEAPI";
export const DEACTIVATEAPI = "DEACTIVATEAPI";
export const DASHBOARDAPI = "DASHBOARDAPI";